# com.rpcclient.rpc
rpc.service.nacos.user=nacos
rpc.service.nacos.password=nacos
rpc.service.nacos.address=127.0.0.1:8848
rpc.service.call-timeout-ms = 3000
rpc.service.router.retry=3
rpc.service.router.blacklist-ttl-ms=30000

# 日志
logging.level.root = info

management.endpoints.web.exposure.include=health,metrics


server.port=8881