# com.rpcclient.rpc
rpc.service.nacos.user=nacos
rpc.service.nacos.password=nacos
rpc.service.nacos.address=127.0.0.1:8848
rpc.service.call-timeout-ms = 3000
rpc.service.call-max=100000
rpc.service.router.retry=3
rpc.service.router.blacklist-ttl-ms=30000


# 日志
logging.level.root = info

management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.prometheus.enabled = true
management.metrics.tags.application = "rpc-client"

server.port=8892
server.address=localhost