# com.rpcclient.rpc
rpc.service.nacos.user=nacos
rpc.service.nacos.password=nacos
rpc.service.nacos.address=127.0.0.1:8848
rpc.service.timeout = 3000
rpc.service.retry=3

# 日志
logging.level.root = info