global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # 抓你的 RPC 应用
  - job_name: "rpc"
    metrics_path: "/actuator/prometheus"
    scheme: http
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:8892"]
        labels:
          app: "rpc"
          env: "dev"