package protoc.hello;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

public interface HelloWorldResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloWorldResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string res = 1;</code>
   */
  String getRes();
  /**
   * <code>string res = 1;</code>
   */
  com.google.protobuf.ByteString
      getResBytes();
}
